spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dbpicpay?useSSL=false&serverTimezone=America/Sao_Paulo
    username: root
    password: Hu93209147@
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

client:
  authorization-service:
    url: https://mocki.io/v1/6c16be96-7169-494d-9330-3884b468cdc7
  notification-service:
    url: https://mocki.io/v1/6c16be96-7169-494d-9330-3884b468cdc7
